name: Test workspace

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: Linux with all features
    runs-on: ubuntu-latest
    steps:
      - name: Prepare musl-tools
        run: sudo apt-get install musl-tools -y
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
  linux-minimal:
    name: Linux without default features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features